
# Find PThreads4w Include/Library on Windows.

find_path(PTHREADS4W_INCLUDE_DIR
  NAMES pthread.h
  PATH_SUFFIXES include
)
find_library(PTHREADS4W_LIBRARY_DEBUG
  NAMES pthreadVSE3d pthreadVC3d pthreadVCE3d
  PATH_SUFFIXES lib
)
find_library(PTHREADS4W_LIBRARY_RELEASE
  NAMES pthreadVSE3 pthreadVC3 pthreadVCE3
  PATH_SUFFIXES lib
)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(PThreads4w REQUIRED_VARS PTHREADS4W_INCLUDE_DIR PTHREADS4W_LIBRARY_RELEASE PTHREADS4W_LIBRARY_DEBUG)

if (PTHREADS4W_FOUND)
  set(PTHREADS4W_LIBRARIES optimized ${PTHREADS4W_LIBRARY_RELEASE} debug ${PTHREADS4W_LIBRARY_DEBUG})
  set(PTHREADS4W_INCLUDE_DIRS ${PTHREADS4W_INCLUDE_DIR})
  set(PTHREADS4W_DEFINITIONS -DPTW32_STATIC_LIB) 
endif()

mark_as_advanced(PTHREADS4W_INCLUDE_DIR PTHREADS4W_LIBRARY_DEBUG PTHREADS4W_LIBRARY_RELEASE)