



if(${BUILDLOG})
    set(BUILDINFO_FILE "${CMAKE_BINARY_DIR}/BuildInfo.txt")
    file(WRITE ${BUILDINFO_FILE}
        "
Building Form version:  ${FORM_MAJOR_VERSION}.${FORM_MINOR_VERSION}.${FORM_PATCH_VERSION}
Build Platform:         ${CMAKE_HOST_SYSTEM_NAME} ${CMAKE_HOST_SYSTEM_VERSION} ${CMAKE_HOST_SYSTEM_PROCESSOR}
Build Target:           ${CMAKE_SYSTEM_NAME} ${CMAKE_SYSTEM_VERSION} ${CMAKE_SYSTEM_PROCESSOR}
Build Type:             ${CMAKE_BUILD_TYPE}
BUILD Info:

CMAKE_VERSION:          ${CMAKE_VERSION}
CMAKE_C_COMPILER:       ${CMAKE_C_COMPILER_ID} ${CMAKE_C_COMPILER_ARCHITECTURE_ID} ${CMAKE_C_COMPILER_VERSION}
CMAKE_CXX_COMPILER:     ${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_ARCHITECTURE_ID} ${CMAKE_CXX_COMPILER_VERSION}
CMAKE_GENERATOR:        ${CMAKE_GENERATOR}

FORM:                   ${BUILD_FORM}
TFORM:                  ${BUILD_TFORM}
PFORM:                  ${BUILD_PFORM}
WITH_FLOAT:             ${WITH_FLOAT}
WITH_MODULEFILES:       ${WITH_MODULEFILES}
        ")
endif()